site_name: SM2 Wiki
site_description: Wiki for SM2 scholars
site_author: SM2-wiki Team
site_url: https://sm2-wiki.github.io/SM2-wiki/

repo_name: 'SM2-wiki'
repo_url: 'https://github.com/SM2-wiki/SM2-wiki'
edit_uri: 'edit/master/docs/'


copyright: 'Copyright &copy; 2019 SM2-wiki Team'

google_analytics:
  - 'UA-148396512-1'
  - 'auto'
  
nav:

   - 主页:
      - Welcome to SM2 Wiki!: index.md
      - 关于: intro/about.md
      - 如何做出贡献: intro/htc.md
      - Github 操作指北: intro/git_ins.md
      - 编辑格式指示: intro/edit_ins.md
   - 省试/校试:
      - 简介: pro_school_test/index.md
      - 省试: 
        - 江西省省试: pro_school_test/pro/jx.md
        - 吉林省省试: pro_school_test/pro/jl.md
   - 笔试:
      - 简介: exam/index.md
      - 数学:
        - 函数: exam/math/function.md
        - 组合数学: exam/math/combination.md
        - 平面几何: exam/math/geometry.md
      - 物理:
        - 力学: exam/physics/mechanics.md
        - 电磁学: exam/physics/electromagnetism.md
        - 光学: exam/physics/optics.md
        - 热力学: exam/physics/thermodynamics.md
      - 向性测试: 
        - 向性测试: exam/GAT/GAT.md
   - 面试:
      - 简介: interview/index.md
      - 如何准备: interview/prepare.md
      - 注意事项: interview/notice.md 
   - 上坡指南:
      - 简介: guide/index.md
      - 物品清单: guide/list.md
      - 预科生活预览: guide/preview.md

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'blue'
    accent: 'red'
  feature:
    tabs: true
  font: 
    text: 'Fira Sans'
    code: 'Roboto Mono'
  
extra:
  #disqus: 'SM2-wiki'
  pagetime: 'on'
  copyright: '<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh">CC BY-NC-SA 4.0</a>'
  manifest: 'manifest.webmanifest'
  disqus: 'SM2-wiki'
  social:
    - type: github
      link: https://github.com/SM2-wiki
  search:
    language: 'jp'
  
extra_javascript:
 # - '_static/js/extra.js?v=15'
  - '_static/js/jquery-3.2.1.min.js'
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - _static/css/extra.css


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      #emoji_generator: !!python/name:pymdownx.emoji.to_png
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde


